"""Shared domain schemas (enums, models, knowledge-graph types)."""

from traffic_os.schemas.enums import (
    ActionType,
    CollisionKind,
    EmergencyType,
    EventType,
    IncidentStatus,
    IncidentType,
    ReportType,
    RoadHealthKind,
    ScenarioOp,
    SignalMode,
    VehicleClass,
    ViolationType,
    WeatherKind,
)
from traffic_os.schemas.kg import CausalFactor, KGEdge, KGNode
from traffic_os.schemas.models import (
    AccidentRisk,
    AuditLog,
    Camera,
    CameraFrameMetric,
    CitizenReport,
    CityEvent,
    CollisionEvent,
    Detection,
    EconomicImpact,
    EmergencyVehicle,
    Forecast,
    GreenCorridor,
    Incident,
    InfraScenario,
    Junction,
    Recommendation,
    RoadHealthIssue,
    RoadSegment,
    ScenarioEdit,
    ScenarioResult,
    SegmentMetric,
    Signal,
    SignalPhase,
    SignalState,
    Track,
    TrackPoint,
    Violation,
    Weather,
)

__all__ = [
    # enums
    "ActionType",
    "CollisionKind",
    "EmergencyType",
    "EventType",
    "IncidentStatus",
    "IncidentType",
    "ReportType",
    "RoadHealthKind",
    "ScenarioOp",
    "SignalMode",
    "VehicleClass",
    "ViolationType",
    "WeatherKind",
    # kg
    "CausalFactor",
    "KGEdge",
    "KGNode",
    # models
    "AccidentRisk",
    "AuditLog",
    "Camera",
    "CameraFrameMetric",
    "CitizenReport",
    "CityEvent",
    "CollisionEvent",
    "Detection",
    "EconomicImpact",
    "EmergencyVehicle",
    "Forecast",
    "GreenCorridor",
    "Incident",
    "InfraScenario",
    "Junction",
    "Recommendation",
    "RoadHealthIssue",
    "RoadSegment",
    "ScenarioEdit",
    "ScenarioResult",
    "SegmentMetric",
    "Signal",
    "SignalPhase",
    "SignalState",
    "Track",
    "TrackPoint",
    "Violation",
    "Weather",
]
